version: "3.8"
services:
  backend:
    build:
      context: ./backend
    ports:
      - "4000:4000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  frontend:
    build:
      context: ./Frontend/pocketpharma
      dockerfile: Dockerfile # Specify the Dockerfile for the frontend
    ports:
      - "3000:80" # Map frontend service port 80 to host port 3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
    depends_on:
      - backend # Ensure frontend starts after backend

volumes:
  db-data:
