services:
  backend:
    build:
      context: ./backendLogic
    ports:
      - "4000:4000"
    env_file:
      - ./.env
    volumes:
      - ./backendLogic:/app
    depends_on:
      - db

  db:
    image: postgres:15
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  frontend:
    build:
      context: ./Frontend/pocketpharma
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  db-data: